channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.07.19
  - certifi=2022.6.15
  - cffi=1.15.0
  - charset-normalizer=2.0.4
  - cryptography=37.0.1
  - cudatoolkit=11.3.1
  - ffmpeg=4.3
  - freetype=2.11.0
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - idna=3.3
  - intel-openmp=2021.4.0
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.2
  - libpng=1.6.37
  - libstdcxx-ng=11.2.0
  - libtasn1=4.16.0
  - libtiff=4.2.0
  - libunistring=0.9.10
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - lz4-c=1.9.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.3
  - nettle=3.7.3
  - numpy=1.22.3
  - numpy-base=1.22.3
  - openh264=2.1.1
  - openssl=1.1.1
  - pillow=9.2.0
  - pip=22.1.2
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pysocks=1.7.1
  - python=3.8.13
  - pytorch=1.12.0
  - pytorch-mutex=1.0=cuda
  - readline=8.1.2
  - requests=2.28.1
  - setuptools=61.2.0
  - six=1.16.0
  - sqlite=3.38.5
  - tk=8.6.12
  - torchaudio=0.12.0=py38_cu113
  - torchvision=0.13.0=py38_cu113
  - typing_extensions=4.1.1
  - urllib3=1.26.11
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - absl-py==1.2.0
    - addict==2.4.0
    - anyio==3.6.1
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - asttokens==2.0.5
    - attrs==22.1.0
    - babel==2.10.3
    - backcall==0.2.0
    - beautifulsoup4==4.11.1
    - bleach==5.0.1
    - cachetools==5.2.0
    - click==8.1.3
    - cloudpickle==2.1.0
    - cycler==0.11.0
    - debugpy==1.6.2
    - decorator==5.1.1
    - deepdiff==5.8.1
    - defusedxml==0.7.1
    - deprecation==2.1.0
    - entrypoints==0.4
    - executing==0.9.1
    - fastjsonschema==2.16.1
    - flask==2.0.3
    - fonttools==4.34.4
    - google-auth==2.9.1
    - google-auth-oauthlib==0.4.6
    - grpcio==1.48.0
    - gym==0.25.1
    - gym-notices==0.0.7
    - h5py==3.7.0
    - imageio==2.20.0
    - importlib-metadata==4.12.0
    - importlib-resources==5.9.0
    - ipdb==0.13.9
    - ipykernel==6.15.1
    - ipython==8.4.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.7.1
    - itsdangerous==2.1.2
    - jedi==0.18.1
    - jinja2==3.1.2
    - joblib==1.1.0
    - json5==0.9.8
    - jsonschema==4.9.0
    - jupyter-client==7.3.4
    - jupyter-core==4.11.1
    - jupyter-packaging==0.12.2
    - jupyter-server==1.18.1
    - jupyterlab==3.4.4
    - jupyterlab-pygments==0.2.2
    - jupyterlab-server==2.15.0
    - jupyterlab-widgets==1.1.1
    - kiwisolver==1.4.4
    - littleutils==0.2.2
    - lxml==4.9.1
    - markdown==3.4.1
    - markupsafe==2.1.1
    - matplotlib==3.5.1
    - matplotlib-inline==0.1.3
    - mistune==0.8.4
    - nbclassic==0.4.3
    - nbclient==0.6.6
    - nbconvert==6.5.0
    - nbformat==5.4.0
    - nest-asyncio==1.5.5
    - ninja==1.10.2.3
    - notebook==6.4.12
    - notebook-shim==0.1.0
    - oauthlib==3.2.0
    - open3d==0.15.2
    - opencv-python==4.6.0.66
    - ordered-set==4.1.0
    - packaging==21.3
    - pandas==1.4.3
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pkgutil-resolve-name==1.3.10
    - plotly==5.9.0
    - prometheus-client==0.14.1
    - prompt-toolkit==3.0.30
    - protobuf==3.19.4
    - psutil==5.9.1
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pygments==2.12.0
    - pymeshlab==2022.2.post2
    - pyparsing==3.0.9
    - pyquaternion==0.9.9
    - pyrsistent==0.18.1
    - python-dateutil==2.8.2
    - pytz==2022.1
    - pyyaml==6.0
    - pyzmq==23.2.0
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - rtree==1.0.0
    - scikit-learn==1.1.1
    - scipy==1.10.1
    - seaborn==0.11.2
    - send2trash==1.8.0
    - sniffio==1.2.0
    - sorcery==0.2.2
    - soupsieve==2.3.2.post1
    - stack-data==0.3.0
    - tb-nightly==2.10.0a20220731
    - tenacity==8.0.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - terminado==0.15.0
    - threadpoolctl==3.1.0
    - tinycss2==1.1.1
    - toml==0.10.2
    - tomlkit==0.11.1
    - tornado==6.1
    - tqdm==4.64.0
    - traitlets==5.3.0
    - transformations==2021.6.6
    - transforms3d==0.3.1
    - trimesh==4.4.1
    - usd-core==22.8
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - websocket-client==1.3.3
    - werkzeug==2.2.1
    - widgetsnbextension==3.6.1
    - wrapt==1.14.1
    - yapf==0.32.0
    - zipp==3.8.1
